#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Führe das Script zur Entfernung ungenutzter Variablen aus
echo "🔍 Versuche, ungenutzte Variablen automatisch zu entfernen..."
files=$(git diff --cached --name-only --diff-filter=ACM "*.ts" "*.tsx")
if [ -n "$files" ]; then
  node .husky/lint-fix-scripts/fix-unused-vars.js $files
  # Aktualisierte Dateien erneut stagen
  git add $files
fi

# Führe lint-staged aus
npx lint-staged
